### PR TITLE
Make logfile configurable but also STDOUT by default; enable quiet 

### PR DESCRIPTION
**Pull request by jhart-r7**
Just a minor modification -- makes this log to `STDOUT` by default but makes the log path configurable should you still want to log to a file.  The rest of the changes are just removing EOL whitespace, which my editor does by default -- sorry.

Update: this also addresses @sjhilt's request that it log to `STDOUT` and the specified/default log file by default, but also has a quiet mode where it only logs to the specified/default log file and not to `STDOUT`.  While here I also cleaned up the logging code a bit.

### CODE REVIEW

**Comment by sjhilt** [comment]
I would always like it to log by default, how about to always log to both by default, and then you can specify new log file, or an option to make it silent to STDOUT.

**Comment by jhart-r7** [comment]
@sjhilt done.

**Comment by sjhilt** [comment]
Perfect! going to merge now.

**Comment by jhart-r7** [comment]
Ping?

**Comment by sjhilt** [comment]
should be merged, but thought I  moved it in but apparently didn't sorry about that.

**Pull request merged**
